---
- name: "Applications Common - LVMs"
  ansible.builtin.debug:
    msg:
      - app_common.lvms_create: "{{ app_common.lvms_create }}"
      - app_common.vgs_create: "{{ app_common.vgs_create }}"
      - app_common.vgs: "{{ app_common.vgs }}"
      - app_common.disks: "{{ app_common.disks }}"
  when:
    - app_common_role_debug
  tags:
    - app_common
    - app_common_lvms
    - app_common_debug

- name: "Applications Common - LVMs - VGs"
  ansible.builtin.include_tasks: app-vg.yml
  loop: "{{ app_common.vgs }}"
  loop_control:
    loop_var: vg
  when:
    - app_common.vgs_create
  tags:
    - app_common
    - app_common_lvms
    - app_common_vgs
