---
- name: "Applications Common - LVMs - VGs - VG - LV - Debug info : {{ lv.name | default('') }}"
  ansible.builtin.debug:
    msg:
      - vg: "{{ vg }}"
      - lv: "{{ lv }}"
  when:
    - app_common_role_debug | default(false)
    - vg
    - lv
  tags:
    - app_common
    - app_common_lvms
    - app_common_vgs
    - app_common_vg
    - app_common_lvs
    - app_common_lv
    - app_common_debug

- name: "Applications Common - LVMs - VGs - VG - LV - Check LV  : {{ lv.name | default('') }}"
  community.general.lvol:
    vg: "{{ vg.name }}"
    lv: "{{ lv.name }}"
    size: "{{ lv.size }}"
  when:
    - vg.name
    - lv.name
    - lv.size
  tags:
    - app_common
    - app_common_lvms
    - app_common_vgs
    - app_common_vg
    - app_common_lvs
    - app_common_lv

- name: "Applications Common - LVMs - VGs - VG - LV - Check File System : {{ lv.name | default('') }}"
  community.general.filesystem:
    fstype: "{{ lv.fstype }}"
    dev: /dev/mapper/{{ vg.name }}-{{ lv.name }}
    resizefs: true
    
  tags:
    - app_common
    - app_common_lvms
    - app_common_vgs
    - app_common_vg
    - app_common_lvs
    - app_common_lv
    - app_common_fs

- name: "Applications Common - LVMs - VGs - VG - LV - Check Mount Directory : {{ lv.name | default('') }}"
  ansible.builtin.file:
    path: "{{ lv.mount_point }}"
    state: directory
    recurse: false
    follow: false
    mode: '0644'
  tags:
    - app_common
    - app_common_lvms
    - app_common_vgs
    - app_common_vg
    - app_common_lvs
    - app_common_lv
    - app_common_directory

- name: "Applications Common - LVMs - VGs - VG - LV - Check Mount Point : {{ lv.name | default('') }}"
  ansible.posix.mount:
    path: "{{ lv.mount_point }}"
    src: "/dev/mapper/{{ vg.name }}-{{ lv.name }}"
    fstype: "{{ lv.fstype }}"
    opts: defaults
    state: present
    backup: true
  tags:
    - app_common
    - app_common_lvms
    - app_common_vgs
    - app_common_vg
    - app_common_lvs
    - app_common_lv
    - app_common_mount_point

...
