---
- name: Applications Common - Debian Familly - Print application Vars
  ansible.builtin.debug:
    msg:
      - "app_common.name : {{ app_common.name }}"
      - "app_common.tag : {{ app_common.tag }}"
      - "app_common.id : {{ app_common.id }}"
      - "app_common.comment : {{ app_common.comment }}"
  when: app_common_role_debug
  tags:
    - app_common
    - app_common_debian
    - app_common_debug

- name: "Applications Common - Debian Familly - Groups"
  ansible.builtin.import_tasks: app-groups.yml
  when:
    - app_common.groups_create
  tags:
    - app_common
    - app_common_debian
    - app_common_groups

- name: "Applications Common - Debian Familly - Users"
  ansible.builtin.import_tasks: app-users.yml
  when:
    - app_common.users_create
  tags:
    - app_common
    - app_common_debian
    - app_common_users

- name: "Applications Common - Debian Familly - Directories"
  ansible.builtin.import_tasks: app-directories.yml
  when:
    - app_common.directories_create
  tags:
    - app_common
    - app_common_debian
    - app_common_directories

- name: "Applications Common - Debian Familly - LVMs"
  ansible.builtin.import_tasks: app-lvms.yml
  when:
    - ansible_virtualization_type != "lxc"
    - ansible_virtualization_type != "docker"
    - app_common.lvms_create
  tags:
    - app_common
    - app_common_debian
    - app_common_lvms
