---
# Loading OS correct vars
- name: Applications Common - Vars - Load
  ansible.builtin.import_tasks: load_vars.yml
  tags:
    - app_common
    - app_common_vars
    - app_common_vars_load

- name: Applications Common - Vars - Print
  ansible.builtin.debug:
    msg:
      - "app_common : {{ app_common }}"
  tags:
    - app_common
    - app_common_vars
    - app_common_vars_debug

- name: Applications Common - Deploy common role on RHEL Familly
  ansible.builtin.import_tasks: rhel-main.yml
  when: ( ansible_os_family == 'RedHat' or ansible_os_family == 'Rocky' )
  tags:
    - app_common
    - app_common_rhel

- name: Applications Common - Deploy common role on Debian Familly
  ansible.builtin.import_tasks: debian-main.yml
  when: (ansible_facts['os_family'] == "Debian")
  tags:
    - app_common
    - app_common_debian
