---
- name: Applications Common - RedHat Familly - Print application Vars
  ansible.builtin.debug:
    msg:
      - "Application Name : {{ app_common.name }}"
      - "Application Tag : {{ app_common.tag }}"
      - "Application id : {{ app_common.id }}"
      - "Application comment : {{ app_common.comment }}"
  when: app_common_role_debug
  tags:
    - role_debug

- name: "Applications Common - RedHat Familly - Groups"
  ansible.builtin.import_tasks: app-groups.yml
  when:
    - app_common.groups_create
  tags:
    - create_groups

- name: "Applications Common - RedHat Familly - Users"
  ansible.builtin.import_tasks: app-users.yml
  when:
    - app_common.users_create
  tags:
    - create_users

- name: "Applications Common - RedHat Familly - Application Directories"
  ansible.builtin.import_tasks: app-directories.yml
  when:
    - app_common.directories_create
  tags:
    - create_directories

- name: "Applications Common - Debian Familly - LVMs"
  ansible.builtin.import_tasks: app-lvms.yml
  when:
    - ansible_virtualization_type != "lxc"
    - ansible_virtualization_type != "docker"
    - app_common.lvms_create
  tags:
    - app_common
    - app_common_debian
    - app_common_lvms
