---
- name: Converge
  hosts: all
  become: true

  roles:
    - role: app-common

  vars:
    app_common_role_debug: true

    application:
      name: "My Test Application"
      tag: APTEST
      id: aptest
      comment: "My TEST Application"

    app_common:
      groups_create: true
      groups:
        - name: groupe_one
        - name: groupe_two

      users_create: true
      users:
        - login: "{{ application.id }}"
          comment: "{{ application.comment }}"
          home_directory: "/app/{{ application.tag }}/application"
          base_directory: "/app/{{ application.tag }}"
          shell: "/usr/sbin/nologin"
          group: "{{ application.id }}"
          groups:
            - groupe_one
            - groupe_two

      lvms_create: true
      vgs_create: true
      vgs:
        - name: "vg_app"
          tag: "APTEST"
          lvs_create: true
          lvs:
            - name: "lv_app"
              size: '10g'
              fstype: 'xfs'
              mode: 755
              mount_point: /app/{{ application.tag }}/application
            - name: "lv_log"
              size: '10g'
              fstype: 'xfs'
              mode: 755
              mount_point: /app/{{ application.tag }}/log
            - name: "lv_data"
              size: '10g'
              fstype: 'xfs'
              mode: 755
              mount_point: /app/{{ application.tag }}/data


      directories:
        - path: "/app/{{ application.tag }}/application"
          owner: "{{ application.id }}"
          group: "{{ application.id }}"
          mode: 755
        - path: "/app/{{ application.tag }}/log"
          owner: "{{ application.id }}"
          group: "{{ application.id }}"
          mode: 755
        - path: "/app/{{ application.tag }}/data"
          owner: "{{ application.id }}"
          group: "{{ application.id }}"
          mode: 755

      disks:
        - path: '/dev/disk/azure/scsi1/lun1'
          tag: APTEST
        - path: '/dev/sdc'
          tag: APTEST
        - path: '/dev/sde'
          tag: AFFFF
